import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { COURSES_ENDPOINT } from '../config/api.config';

export const IMAGE_BASE_URL = 'http://localhost:2999/';

export interface Course {
  _id?: string; // Optional, as it might be generated by the backend
  name: string;
  type: string;
  category: string;
  description: string;
  tag?: string;
  price: number;
  discountType: 'Percentage' | 'Fixed';
  discount: number;
  finalPrice: number;
  rating?: number;
  imagePath?: string;
  active: boolean;
}

@Injectable({
  providedIn: 'root'
})
export class CourseService {
  constructor(private http: HttpClient) {}

  getCourses(): Observable<Course[]> {
    return this.http.get<Course[]>(COURSES_ENDPOINT);
  }

  getCourseById(id: string): Observable<Course> {
    return this.http.get<Course>(`${COURSES_ENDPOINT}/${id}`);
  }

  createCourse(course: Course | FormData): Observable<Course> {
    return this.http.post<Course>(COURSES_ENDPOINT, course);
  }

  updateCourse(id: string, course: Course | FormData): Observable<Course> {
    return this.http.put<Course>(`${COURSES_ENDPOINT}/${id}`, course);
  }

  deleteCourse(id: string): Observable<void> {
    return this.http.delete<void>(`${COURSES_ENDPOINT}/${id}`);
  }

  uploadImage(file: File): Observable<{ imagePath: string }> {
    const formData = new FormData();
    formData.append('image', file);
    return this.http.post<{ imagePath: string }>(`${COURSES_ENDPOINT}/upload`, formData);
  }
}